package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * affiliation モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AffiliationDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** manager_base. */
	private ManagerBaseDto managerBase;

	/** affiliation_name. */
	private String affiliationName;

	/** address. */
	private String address;

	/** type_industry_code. */
	private String typeIndustryCode;

	/** activities. */
	private String activities;

	/** register_name. */
	private String registerName;

	/** register_date. */
	private Date registerDate;

	/** update_name. */
	private String updateName;

	/** update_date. */
	private Date updateDate;

	/**
	 * コンストラクタ.
	 */
	public AffiliationDto() {
	}

	/**
	 * manager_base を設定します.
	 * 
	 * @param managerBase
	 *            manager_base
	 */
	public void setManagerBase(ManagerBaseDto managerBase) {
		this.managerBase = managerBase;
	}

	/**
	 * manager_base を取得します.
	 * 
	 * @return manager_base
	 */
	public ManagerBaseDto getManagerBase() {
		return this.managerBase;
	}

	/**
	 * affiliation_name を設定します.
	 * 
	 * @param affiliationName
	 *            affiliation_name
	 */
	public void setAffiliationName(String affiliationName) {
		this.affiliationName = affiliationName;
	}

	/**
	 * affiliation_name を取得します.
	 * 
	 * @return affiliation_name
	 */
	public String getAffiliationName() {
		return this.affiliationName;
	}

	/**
	 * address を設定します.
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * address を取得します.
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * type_industry_code を設定します.
	 * 
	 * @param typeIndustryCode
	 *            type_industry_code
	 */
	public void setTypeIndustryCode(String typeIndustryCode) {
		this.typeIndustryCode = typeIndustryCode;
	}

	/**
	 * type_industry_code を取得します.
	 * 
	 * @return type_industry_code
	 */
	public String getTypeIndustryCode() {
		return this.typeIndustryCode;
	}

	/**
	 * activities を設定します.
	 * 
	 * @param activities
	 *            activities
	 */
	public void setActivities(String activities) {
		this.activities = activities;
	}

	/**
	 * activities を取得します.
	 * 
	 * @return activities
	 */
	public String getActivities() {
		return this.activities;
	}

	/**
	 * register_name を設定します.
	 * 
	 * @param registerName
	 *            register_name
	 */
	public void setRegisterName(String registerName) {
		this.registerName = registerName;
	}

	/**
	 * register_name を取得します.
	 * 
	 * @return register_name
	 */
	public String getRegisterName() {
		return this.registerName;
	}

	/**
	 * register_date を設定します.
	 * 
	 * @param registerDate
	 *            register_date
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * register_date を取得します.
	 * 
	 * @return register_date
	 */
	public Date getRegisterDate() {
		return this.registerDate;
	}

	/**
	 * update_name を設定します.
	 * 
	 * @param updateName
	 *            update_name
	 */
	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	/**
	 * update_name を取得します.
	 * 
	 * @return update_name
	 */
	public String getUpdateName() {
		return this.updateName;
	}

	/**
	 * update_date を設定します.
	 * 
	 * @param updateDate
	 *            update_date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * update_date を取得します.
	 * 
	 * @return update_date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((managerBase == null) ? 0 : managerBase.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AffiliationDto other = (AffiliationDto) obj;
		if (managerBase == null) {
			if (other.managerBase != null) {
				return false;
			}
		} else if (!managerBase.equals(other.managerBase)) {
			return false;
		}
		return true;
	}

}
