package com.soramame.web.biz.dto;

import java.io.Serializable;

/**
 * age_group_mst モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AgeGroupMstDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** age_group_code. */
	private String ageGroupCode;

	/** age_group_name. */
	private String ageGroupName;

	/** sort_number. */
	private Integer sortNumber;

	/**
	 * コンストラクタ.
	 */
	public AgeGroupMstDto() {
	}

	/**
	 * age_group_code を設定します.
	 * 
	 * @param ageGroupCode
	 *            age_group_code
	 */
	public void setAgeGroupCode(String ageGroupCode) {
		this.ageGroupCode = ageGroupCode;
	}

	/**
	 * age_group_code を取得します.
	 * 
	 * @return age_group_code
	 */
	public String getAgeGroupCode() {
		return this.ageGroupCode;
	}

	/**
	 * age_group_name を設定します.
	 * 
	 * @param ageGroupName
	 *            age_group_name
	 */
	public void setAgeGroupName(String ageGroupName) {
		this.ageGroupName = ageGroupName;
	}

	/**
	 * age_group_name を取得します.
	 * 
	 * @return age_group_name
	 */
	public String getAgeGroupName() {
		return this.ageGroupName;
	}

	/**
	 * sort_number を設定します.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number を取得します.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ageGroupCode == null) ? 0 : ageGroupCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AgeGroupMstDto other = (AgeGroupMstDto) obj;
		if (ageGroupCode == null) {
			if (other.ageGroupCode != null) {
				return false;
			}
		} else if (!ageGroupCode.equals(other.ageGroupCode)) {
			return false;
		}
		return true;
	}

}
