package com.soramame.web.biz.dto;

import java.io.Serializable;

/**
 * job_category_mst モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class JobCategoryMstDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** job_category_code. */
	private String jobCategoryCode;

	/** job_category_name. */
	private String jobCategoryName;

	/** sort_number. */
	private Integer sortNumber;

	/**
	 * コンストラクタ.
	 */
	public JobCategoryMstDto() {
	}

	/**
	 * job_category_code を設定します.
	 * 
	 * @param jobCategoryCode
	 *            job_category_code
	 */
	public void setJobCategoryCode(String jobCategoryCode) {
		this.jobCategoryCode = jobCategoryCode;
	}

	/**
	 * job_category_code を取得します.
	 * 
	 * @return job_category_code
	 */
	public String getJobCategoryCode() {
		return this.jobCategoryCode;
	}

	/**
	 * job_category_name を設定します.
	 * 
	 * @param jobCategoryName
	 *            job_category_name
	 */
	public void setJobCategoryName(String jobCategoryName) {
		this.jobCategoryName = jobCategoryName;
	}

	/**
	 * job_category_name を取得します.
	 * 
	 * @return job_category_name
	 */
	public String getJobCategoryName() {
		return this.jobCategoryName;
	}

	/**
	 * sort_number を設定します.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number を取得します.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((jobCategoryCode == null) ? 0 : jobCategoryCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		JobCategoryMstDto other = (JobCategoryMstDto) obj;
		if (jobCategoryCode == null) {
			if (other.jobCategoryCode != null) {
				return false;
			}
		} else if (!jobCategoryCode.equals(other.jobCategoryCode)) {
			return false;
		}
		return true;
	}

}
