package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * manager_base モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ManagerBaseDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_name. */
	private String userName;

	/** password. */
	private String password;

	/** birth_day. */
	private String birthDay;

	/** email. */
	private String email;

	/** live_code. */
	private String liveCode;

	/** register_name. */
	private String registerName;

	/** register_date. */
	private Date registerDate;

	/** update_name. */
	private String updateName;

	/** update_date. */
	private Date updateDate;

	/** affiliation 一覧. */
	private Set<AffiliationDto> affiliationSet;

	/** project 一覧. */
	private Set<ProjectDto> projectSet;

	/** manager_career_overview 一覧. */
	private Set<ManagerCareerOverviewDto> managerCareerOverviewSet;

	/**
	 * コンストラクタ.
	 */
	public ManagerBaseDto() {
		this.affiliationSet = new HashSet<AffiliationDto>();
		this.managerCareerOverviewSet = new HashSet<ManagerCareerOverviewDto>();
		this.projectSet = new HashSet<ProjectDto>();
	}

	/**
	 * user_name を設定します.
	 * 
	 * @param userName
	 *            user_name
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * user_name を取得します.
	 * 
	 * @return user_name
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * password を設定します.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * password を取得します.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * birth_day を設定します.
	 * 
	 * @param birthDay
	 *            birth_day
	 */
	public void setBirthDay(String birthDay) {
		this.birthDay = birthDay;
	}

	/**
	 * birth_day を取得します.
	 * 
	 * @return birth_day
	 */
	public String getBirthDay() {
		return this.birthDay;
	}

	/**
	 * email を設定します.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * email を取得します.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * live_code を設定します.
	 * 
	 * @param liveCode
	 *            live_code
	 */
	public void setLiveCode(String liveCode) {
		this.liveCode = liveCode;
	}

	/**
	 * live_code を取得します.
	 * 
	 * @return live_code
	 */
	public String getLiveCode() {
		return this.liveCode;
	}

	/**
	 * register_name を設定します.
	 * 
	 * @param registerName
	 *            register_name
	 */
	public void setRegisterName(String registerName) {
		this.registerName = registerName;
	}

	/**
	 * register_name を取得します.
	 * 
	 * @return register_name
	 */
	public String getRegisterName() {
		return this.registerName;
	}

	/**
	 * register_date を設定します.
	 * 
	 * @param registerDate
	 *            register_date
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * register_date を取得します.
	 * 
	 * @return register_date
	 */
	public Date getRegisterDate() {
		return this.registerDate;
	}

	/**
	 * update_name を設定します.
	 * 
	 * @param updateName
	 *            update_name
	 */
	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	/**
	 * update_name を取得します.
	 * 
	 * @return update_name
	 */
	public String getUpdateName() {
		return this.updateName;
	}

	/**
	 * update_date を設定します.
	 * 
	 * @param updateDate
	 *            update_date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * update_date を取得します.
	 * 
	 * @return update_date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * affiliation 一覧を設定します.
	 * 
	 * @param affiliationSet
	 *            affiliation 一覧
	 */
	public void setAffiliationSet(Set<AffiliationDto> affiliationSet) {
		this.affiliationSet = affiliationSet;
	}

	/**
	 * affiliation を追加します.
	 * 
	 * @param affiliation
	 *            affiliation
	 */
	public void addAffiliation(AffiliationDto affiliation) {
		this.affiliationSet.add(affiliation);
	}

	/**
	 * affiliation 一覧を取得します.
	 * 
	 * @return affiliation 一覧
	 */
	public Set<AffiliationDto> getAffiliationSet() {
		return this.affiliationSet;
	}

	/**
	 * project 一覧を設定します.
	 * 
	 * @param projectSet
	 *            project 一覧
	 */
	public void setProjectSet(Set<ProjectDto> projectSet) {
		this.projectSet = projectSet;
	}

	/**
	 * project を追加します.
	 * 
	 * @param project
	 *            project
	 */
	public void addProject(ProjectDto project) {
		this.projectSet.add(project);
	}

	/**
	 * project 一覧を取得します.
	 * 
	 * @return project 一覧
	 */
	public Set<ProjectDto> getProjectSet() {
		return this.projectSet;
	}

	/**
	 * manager_career_overview 一覧を設定します.
	 * 
	 * @param managerCareerOverviewSet
	 *            manager_career_overview 一覧
	 */
	public void setManagerCareerOverviewSet(Set<ManagerCareerOverviewDto> managerCareerOverviewSet) {
		this.managerCareerOverviewSet = managerCareerOverviewSet;
	}

	/**
	 * manager_career_overview を追加します.
	 * 
	 * @param managerCareerOverview
	 *            manager_career_overview
	 */
	public void addManagerCareerOverview(ManagerCareerOverviewDto managerCareerOverview) {
		this.managerCareerOverviewSet.add(managerCareerOverview);
	}

	/**
	 * manager_career_overview 一覧を取得します.
	 * 
	 * @return manager_career_overview 一覧
	 */
	public Set<ManagerCareerOverviewDto> getManagerCareerOverviewSet() {
		return this.managerCareerOverviewSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userName == null) ? 0 : userName.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ManagerBaseDto other = (ManagerBaseDto) obj;
		if (userName == null) {
			if (other.userName != null) {
				return false;
			}
		} else if (!userName.equals(other.userName)) {
			return false;
		}
		return true;
	}

}
