package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * participation_hope_counter モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ParticipationHopeCounterDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** project. */
	private ProjectDto project;

	/** participation_hope_count. */
	private Integer participationHopeCount;

	/** participation_hope_date. */
	private Date participationHopeDate;

	/**
	 * コンストラクタ.
	 */
	public ParticipationHopeCounterDto() {
	}

	/**
	 * project を設定します.
	 * 
	 * @param project
	 *            project
	 */
	public void setProject(ProjectDto project) {
		this.project = project;
	}

	/**
	 * project を取得します.
	 * 
	 * @return project
	 */
	public ProjectDto getProject() {
		return this.project;
	}

	/**
	 * participation_hope_count を設定します.
	 * 
	 * @param participationHopeCount
	 *            participation_hope_count
	 */
	public void setParticipationHopeCount(Integer participationHopeCount) {
		this.participationHopeCount = participationHopeCount;
	}

	/**
	 * participation_hope_count を取得します.
	 * 
	 * @return participation_hope_count
	 */
	public Integer getParticipationHopeCount() {
		return this.participationHopeCount;
	}

	/**
	 * participation_hope_date を設定します.
	 * 
	 * @param participationHopeDate
	 *            participation_hope_date
	 */
	public void setParticipationHopeDate(Date participationHopeDate) {
		this.participationHopeDate = participationHopeDate;
	}

	/**
	 * participation_hope_date を取得します.
	 * 
	 * @return participation_hope_date
	 */
	public Date getParticipationHopeDate() {
		return this.participationHopeDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((project == null) ? 0 : project.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ParticipationHopeCounterDto other = (ParticipationHopeCounterDto) obj;
		if (project == null) {
			if (other.project != null) {
				return false;
			}
		} else if (!project.equals(other.project)) {
			return false;
		}
		return true;
	}

}
