package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * player_career_overview モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PlayerCareerOverviewDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** career_id. */
	private String careerId;

	/** player_base. */
	private PlayerBaseDto playerBase;

	/** affiliation_name. */
	private String affiliationName;

	/** job_category_code. */
	private String jobCategoryCode;

	/** period_from. */
	private String periodFrom;

	/** period_to. */
	private String periodTo;

	/** over_view. */
	private String overView;

	/** register_name. */
	private String registerName;

	/** register_date. */
	private Date registerDate;

	/** update_name. */
	private String updateName;

	/** update_date. */
	private Date updateDate;

	/**
	 * コンストラクタ.
	 */
	public PlayerCareerOverviewDto() {
	}

	/**
	 * career_id を設定します.
	 * 
	 * @param careerId
	 *            career_id
	 */
	public void setCareerId(String careerId) {
		this.careerId = careerId;
	}

	/**
	 * career_id を取得します.
	 * 
	 * @return career_id
	 */
	public String getCareerId() {
		return this.careerId;
	}

	/**
	 * player_base を設定します.
	 * 
	 * @param playerBase
	 *            player_base
	 */
	public void setPlayerBase(PlayerBaseDto playerBase) {
		this.playerBase = playerBase;
	}

	/**
	 * player_base を取得します.
	 * 
	 * @return player_base
	 */
	public PlayerBaseDto getPlayerBase() {
		return this.playerBase;
	}

	/**
	 * affiliation_name を設定します.
	 * 
	 * @param affiliationName
	 *            affiliation_name
	 */
	public void setAffiliationName(String affiliationName) {
		this.affiliationName = affiliationName;
	}

	/**
	 * affiliation_name を取得します.
	 * 
	 * @return affiliation_name
	 */
	public String getAffiliationName() {
		return this.affiliationName;
	}

	/**
	 * job_category_code を設定します.
	 * 
	 * @param jobCategoryCode
	 *            job_category_code
	 */
	public void setJobCategoryCode(String jobCategoryCode) {
		this.jobCategoryCode = jobCategoryCode;
	}

	/**
	 * job_category_code を取得します.
	 * 
	 * @return job_category_code
	 */
	public String getJobCategoryCode() {
		return this.jobCategoryCode;
	}

	/**
	 * period_from を設定します.
	 * 
	 * @param periodFrom
	 *            period_from
	 */
	public void setPeriodFrom(String periodFrom) {
		this.periodFrom = periodFrom;
	}

	/**
	 * period_from を取得します.
	 * 
	 * @return period_from
	 */
	public String getPeriodFrom() {
		return this.periodFrom;
	}

	/**
	 * period_to を設定します.
	 * 
	 * @param periodTo
	 *            period_to
	 */
	public void setPeriodTo(String periodTo) {
		this.periodTo = periodTo;
	}

	/**
	 * period_to を取得します.
	 * 
	 * @return period_to
	 */
	public String getPeriodTo() {
		return this.periodTo;
	}

	/**
	 * over_view を設定します.
	 * 
	 * @param overView
	 *            over_view
	 */
	public void setOverView(String overView) {
		this.overView = overView;
	}

	/**
	 * over_view を取得します.
	 * 
	 * @return over_view
	 */
	public String getOverView() {
		return this.overView;
	}

	/**
	 * register_name を設定します.
	 * 
	 * @param registerName
	 *            register_name
	 */
	public void setRegisterName(String registerName) {
		this.registerName = registerName;
	}

	/**
	 * register_name を取得します.
	 * 
	 * @return register_name
	 */
	public String getRegisterName() {
		return this.registerName;
	}

	/**
	 * register_date を設定します.
	 * 
	 * @param registerDate
	 *            register_date
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * register_date を取得します.
	 * 
	 * @return register_date
	 */
	public Date getRegisterDate() {
		return this.registerDate;
	}

	/**
	 * update_name を設定します.
	 * 
	 * @param updateName
	 *            update_name
	 */
	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	/**
	 * update_name を取得します.
	 * 
	 * @return update_name
	 */
	public String getUpdateName() {
		return this.updateName;
	}

	/**
	 * update_date を設定します.
	 * 
	 * @param updateDate
	 *            update_date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * update_date を取得します.
	 * 
	 * @return update_date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((careerId == null) ? 0 : careerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PlayerCareerOverviewDto other = (PlayerCareerOverviewDto) obj;
		if (careerId == null) {
			if (other.careerId != null) {
				return false;
			}
		} else if (!careerId.equals(other.careerId)) {
			return false;
		}
		return true;
	}

}
