package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * player_scout_counter モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PlayerScoutCounterDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** player_base. */
	private PlayerBaseDto playerBase;

	/** player_scout_count. */
	private Integer playerScoutCount;

	/** scout_date. */
	private Date scoutDate;

	/**
	 * コンストラクタ.
	 */
	public PlayerScoutCounterDto() {
	}

	/**
	 * player_base を設定します.
	 * 
	 * @param playerBase
	 *            player_base
	 */
	public void setPlayerBase(PlayerBaseDto playerBase) {
		this.playerBase = playerBase;
	}

	/**
	 * player_base を取得します.
	 * 
	 * @return player_base
	 */
	public PlayerBaseDto getPlayerBase() {
		return this.playerBase;
	}

	/**
	 * player_scout_count を設定します.
	 * 
	 * @param playerScoutCount
	 *            player_scout_count
	 */
	public void setPlayerScoutCount(Integer playerScoutCount) {
		this.playerScoutCount = playerScoutCount;
	}

	/**
	 * player_scout_count を取得します.
	 * 
	 * @return player_scout_count
	 */
	public Integer getPlayerScoutCount() {
		return this.playerScoutCount;
	}

	/**
	 * scout_date を設定します.
	 * 
	 * @param scoutDate
	 *            scout_date
	 */
	public void setScoutDate(Date scoutDate) {
		this.scoutDate = scoutDate;
	}

	/**
	 * scout_date を取得します.
	 * 
	 * @return scout_date
	 */
	public Date getScoutDate() {
		return this.scoutDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((playerBase == null) ? 0 : playerBase.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PlayerScoutCounterDto other = (PlayerScoutCounterDto) obj;
		if (playerBase == null) {
			if (other.playerBase != null) {
				return false;
			}
		} else if (!playerBase.equals(other.playerBase)) {
			return false;
		}
		return true;
	}

}
