package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * project_access_counter モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProjectAccessCounterDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** project. */
	private ProjectDto project;

	/** project_access_count. */
	private Integer projectAccessCount;

	/** access_date. */
	private Date accessDate;

	/**
	 * コンストラクタ.
	 */
	public ProjectAccessCounterDto() {
	}

	/**
	 * project を設定します.
	 * 
	 * @param project
	 *            project
	 */
	public void setProject(ProjectDto project) {
		this.project = project;
	}

	/**
	 * project を取得します.
	 * 
	 * @return project
	 */
	public ProjectDto getProject() {
		return this.project;
	}

	/**
	 * project_access_count を設定します.
	 * 
	 * @param projectAccessCount
	 *            project_access_count
	 */
	public void setProjectAccessCount(Integer projectAccessCount) {
		this.projectAccessCount = projectAccessCount;
	}

	/**
	 * project_access_count を取得します.
	 * 
	 * @return project_access_count
	 */
	public Integer getProjectAccessCount() {
		return this.projectAccessCount;
	}

	/**
	 * access_date を設定します.
	 * 
	 * @param accessDate
	 *            access_date
	 */
	public void setAccessDate(Date accessDate) {
		this.accessDate = accessDate;
	}

	/**
	 * access_date を取得します.
	 * 
	 * @return access_date
	 */
	public Date getAccessDate() {
		return this.accessDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((project == null) ? 0 : project.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProjectAccessCounterDto other = (ProjectAccessCounterDto) obj;
		if (project == null) {
			if (other.project != null) {
				return false;
			}
		} else if (!project.equals(other.project)) {
			return false;
		}
		return true;
	}

}
