package com.soramame.web.biz.dto;

import java.io.Serializable;

/**
 * type_industry_mst モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TypeIndustryMstDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** type_industry_code. */
	private String typeIndustryCode;

	/** type_industry_name. */
	private String typeIndustryName;

	/** sort_number. */
	private Integer sortNumber;

	/**
	 * コンストラクタ.
	 */
	public TypeIndustryMstDto() {
	}

	/**
	 * type_industry_code を設定します.
	 * 
	 * @param typeIndustryCode
	 *            type_industry_code
	 */
	public void setTypeIndustryCode(String typeIndustryCode) {
		this.typeIndustryCode = typeIndustryCode;
	}

	/**
	 * type_industry_code を取得します.
	 * 
	 * @return type_industry_code
	 */
	public String getTypeIndustryCode() {
		return this.typeIndustryCode;
	}

	/**
	 * type_industry_name を設定します.
	 * 
	 * @param typeIndustryName
	 *            type_industry_name
	 */
	public void setTypeIndustryName(String typeIndustryName) {
		this.typeIndustryName = typeIndustryName;
	}

	/**
	 * type_industry_name を取得します.
	 * 
	 * @return type_industry_name
	 */
	public String getTypeIndustryName() {
		return this.typeIndustryName;
	}

	/**
	 * sort_number を設定します.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number を取得します.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((typeIndustryCode == null) ? 0 : typeIndustryCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TypeIndustryMstDto other = (TypeIndustryMstDto) obj;
		if (typeIndustryCode == null) {
			if (other.typeIndustryCode != null) {
				return false;
			}
		} else if (!typeIndustryCode.equals(other.typeIndustryCode)) {
			return false;
		}
		return true;
	}

}
