package com.soramame.web.biz.dto;

import java.io.Serializable;

/**
 * numbering モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NumberingDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** numbering_code. */
	private String numberingCode;

	/** id. */
	private String id;

	/**
	 * コンストラクタ.
	 */
	public NumberingDto() {
	}

	/**
	 * numbering_code を設定します.
	 * 
	 * @param numberingCode
	 *            numbering_code
	 */
	public void setNumberingCode(String numberingCode) {
		this.numberingCode = numberingCode;
	}

	/**
	 * numbering_code を取得します.
	 * 
	 * @return numbering_code
	 */
	public String getNumberingCode() {
		return this.numberingCode;
	}

	/**
	 * id を設定します.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * id を取得します.
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numberingCode == null) ? 0 : numberingCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NumberingDto other = (NumberingDto) obj;
		if (numberingCode == null) {
			if (other.numberingCode != null) {
				return false;
			}
		} else if (!numberingCode.equals(other.numberingCode)) {
			return false;
		}
		return true;
	}

}
