package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * participation_hope_counter モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ParticipationHopeCounterDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** project_id. */
	private String projectId;

	/** title. */
	private String title;

	/** participation_hope_count. */
	private Integer participationHopeCount;

	/** participation_hope_date. */
	private Date participationHopeDate;

	/**
	 * コンストラクタ.
	 */
	public ParticipationHopeCounterDto() {
	}

	/**
	 * project_id を設定します.
	 * 
	 * @param projectId
	 *            project_id
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * project_id を取得します.
	 * 
	 * @return project_id
	 */
	public String getProjectId() {
		return this.projectId;
	}

	/**
	 * title を設定します.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * title を取得します.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * participation_hope_count を設定します.
	 * 
	 * @param participationHopeCount
	 *            participation_hope_count
	 */
	public void setParticipationHopeCount(Integer participationHopeCount) {
		this.participationHopeCount = participationHopeCount;
	}

	/**
	 * participation_hope_count を取得します.
	 * 
	 * @return participation_hope_count
	 */
	public Integer getParticipationHopeCount() {
		return this.participationHopeCount;
	}

	/**
	 * participation_hope_date を設定します.
	 * 
	 * @param participationHopeDate
	 *            participation_hope_date
	 */
	public void setParticipationHopeDate(Date participationHopeDate) {
		this.participationHopeDate = participationHopeDate;
	}

	/**
	 * participation_hope_date を取得します.
	 * 
	 * @return participation_hope_date
	 */
	public Date getParticipationHopeDate() {
		return this.participationHopeDate;
	}

}
