package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * project モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProjectDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** project_id. */
	private String projectId;

	/** user_name. */
	private String userName;

	/** title. */
	private String title;

	/** recruitment_area_code. */
	private String recruitmentAreaCode;

	/** over_view. */
	private String overView;

	/** register_name. */
	private String registerName;

	/** register_date. */
	private Date registerDate;

	/** update_name. */
	private String updateName;

	/** update_date. */
	private Date updateDate;

	/** project_access_counter. */
	private ProjectAccessCounterDto projectAccessCounter;

	/** participation_hope_counter. */
	private ParticipationHopeCounterDto participationHopeCounter;
	
	/**
	 * コンストラクタ.
	 */
	public ProjectDto() {
	}

	/**
	 * project_id を設定します.
	 * 
	 * @param projectId
	 *            project_id
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * project_id を取得します.
	 * 
	 * @return project_id
	 */
	public String getProjectId() {
		return this.projectId;
	}

	/**
	 * user_name を設定します.
	 * 
	 * @param user_name
	 *            user_name
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * user_name を取得します.
	 * 
	 * @return user_name
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * title を設定します.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * title を取得します.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * recruitment_area_code を設定します.
	 * 
	 * @param recruitmentAreaCode
	 *            recruitment_area_code
	 */
	public void setRecruitmentAreaCode(String recruitmentAreaCode) {
		this.recruitmentAreaCode = recruitmentAreaCode;
	}

	/**
	 * recruitment_area_code を取得します.
	 * 
	 * @return recruitment_area_code
	 */
	public String getRecruitmentAreaCode() {
		return this.recruitmentAreaCode;
	}

	/**
	 * over_view を設定します.
	 * 
	 * @param overView
	 *            over_view
	 */
	public void setOverView(String overView) {
		this.overView = overView;
	}

	/**
	 * over_view を取得します.
	 * 
	 * @return over_view
	 */
	public String getOverView() {
		return this.overView;
	}

	/**
	 * register_name を設定します.
	 * 
	 * @param registerName
	 *            register_name
	 */
	public void setRegisterName(String registerName) {
		this.registerName = registerName;
	}

	/**
	 * register_name を取得します.
	 * 
	 * @return register_name
	 */
	public String getRegisterName() {
		return this.registerName;
	}

	/**
	 * register_date を設定します.
	 * 
	 * @param registerDate
	 *            register_date
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * register_date を取得します.
	 * 
	 * @return register_date
	 */
	public Date getRegisterDate() {
		return this.registerDate;
	}

	/**
	 * update_name を設定します.
	 * 
	 * @param updateName
	 *            update_name
	 */
	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	/**
	 * update_name を取得します.
	 * 
	 * @return update_name
	 */
	public String getUpdateName() {
		return this.updateName;
	}

	/**
	 * update_date を設定します.
	 * 
	 * @param updateDate
	 *            update_date
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * update_date を取得します.
	 * 
	 * @return update_date
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * project_access_counter を設定します.
	 * 
	 * @param projectAccessCounterSet
	 *            project_access_counter
	 */
	public void setProjectAccessCounter(ProjectAccessCounterDto projectAccessCounter) {
		this.projectAccessCounter = projectAccessCounter;
	}

	/**
	 * project_access_counter を取得します.
	 * 
	 * @return project_access_counter
	 */
	public ProjectAccessCounterDto getProjectAccessCounter() {
		return this.projectAccessCounter;
	}

	/**
	 * participation_hope_counter を設定します.
	 * 
	 * @param participationHopeCounterSet
	 *            participation_hope_counter
	 */
	public void setParticipationHopeCounter(ParticipationHopeCounterDto participationHopeCounter) {
		this.participationHopeCounter = participationHopeCounter;
	}

	/**
	 * participation_hope_counter を取得します.
	 * 
	 * @return participation_hope_counter
	 */
	public ParticipationHopeCounterDto getParticipationHopeCounter() {
		return this.participationHopeCounter;
	}

}
