package com.soramame.web.biz.dto;

import java.io.Serializable;

/**
 * recruitment_area_mst モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RecruitmentAreaMstDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** recruitment_area_code. */
	private String recruitmentAreaCode;

	/** recruitment_area_name. */
	private String recruitmentAreaName;

	/** sort_number. */
	private Integer sortNumber;

	/**
	 * コンストラクタ.
	 */
	public RecruitmentAreaMstDto() {
	}

	/**
	 * recruitment_area_code を設定します.
	 * 
	 * @param recruitmentAreaCode
	 *            recruitmentArea_code
	 */
	public void setRecruitmentAreaCode(String recruitmentAreaCode) {
		this.recruitmentAreaCode = recruitmentAreaCode;
	}

	/**
	 * recruitment_area_code を取得します.
	 * 
	 * @return recruitment_area_code
	 */
	public String getRecruitmentAreaCode() {
		return this.recruitmentAreaCode;
	}

	/**
	 * recruitment_area_name を設定します.
	 * 
	 * @param recruitment_area_name
	 *            recruitment_area_name
	 */
	public void setRecruitmentAreaName(String recruitmentAreaName) {
		this.recruitmentAreaName = recruitmentAreaName;
	}

	/**
	 * recruitment_area_name を取得します.
	 * 
	 * @return recruitment_area_name
	 */
	public String getRecruitmentAreaName() {
		return this.recruitmentAreaName;
	}

	/**
	 * sort_number を設定します.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number を取得します.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((recruitmentAreaCode == null) ? 0 : recruitmentAreaCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RecruitmentAreaMstDto other = (RecruitmentAreaMstDto) obj;
		if (recruitmentAreaCode == null) {
			if (other.recruitmentAreaCode != null) {
				return false;
			}
		} else if (!recruitmentAreaCode.equals(other.recruitmentAreaCode)) {
			return false;
		}
		return true;
	}

}
