package com.soramame.web.biz.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * player_scout_counter モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserScoutCounterDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_name. */
	private String userName;

	/** player_scout_count. */
	private Integer userScoutCount;

	/** scout_date. */
	private Date scoutDate;

	/**
	 * コンストラクタ.
	 */
	public UserScoutCounterDto() {
	}

	/**
	 * user_name を設定します.
	 * 
	 * @param userName
	 *            user_name
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * user_name を取得します.
	 * 
	 * @return user_name
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * player_scout_count を設定します.
	 * 
	 * @param playerScoutCount
	 *            player_scout_count
	 */
	public void setUserScoutCount(Integer playerScoutCount) {
		this.userScoutCount = playerScoutCount;
	}

	/**
	 * player_scout_count を取得します.
	 * 
	 * @return player_scout_count
	 */
	public Integer getUserScoutCount() {
		return this.userScoutCount;
	}

	/**
	 * scout_date を設定します.
	 * 
	 * @param scoutDate
	 *            scout_date
	 */
	public void setScoutDate(Date scoutDate) {
		this.scoutDate = scoutDate;
	}

	/**
	 * scout_date を取得します.
	 * 
	 * @return scout_date
	 */
	public Date getScoutDate() {
		return this.scoutDate;
	}

}
