package com.soramame.web.model;

import java.io.Serializable;

/**
 * age_group_mst ƒ‚ƒfƒ‹ƒNƒ‰ƒX.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AgeGroupMstModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** age_group_code. */
	private String ageGroupCode;

	/** age_group_name. */
	private String ageGroupName;

	/** sort_number. */
	private Integer sortNumber;

	/** select. */
	private String select;
	
	/**
	 * Constructor
	 * @param ageGroupCode
	 * @param ageGroupName
	 * @param select
	 */
	public AgeGroupMstModel(String ageGroupCode, String ageGroupName, String select) {
		this.ageGroupCode = ageGroupCode;
		this.ageGroupName = ageGroupName;
		
		if (select.equals(ageGroupCode)) {
			this.select = "selected";
			
		} else {
			this.select = "";
			
		}
	}

	/**
	 * age_group_code ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param ageGroupCode
	 *            age_group_code
	 */
	public void setAgeGroupCode(String ageGroupCode) {
		this.ageGroupCode = ageGroupCode;
	}

	/**
	 * age_group_code ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return age_group_code
	 */
	public String getAgeGroupCode() {
		return this.ageGroupCode;
	}

	/**
	 * age_group_name ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param ageGroupName
	 *            age_group_name
	 */
	public void setAgeGroupName(String ageGroupName) {
		this.ageGroupName = ageGroupName;
	}

	/**
	 * age_group_name ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return age_group_name
	 */
	public String getAgeGroupName() {
		return this.ageGroupName;
	}

	/**
	 * sort_number ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * @return the select
	 */
	public String getSelect() {
		return select;
	}

	/**
	 * @param select the select to set
	 */
	public void setSelect(String select) {
		this.select = select;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ageGroupCode == null) ? 0 : ageGroupCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AgeGroupMstModel other = (AgeGroupMstModel) obj;
		if (ageGroupCode == null) {
			if (other.ageGroupCode != null) {
				return false;
			}
		} else if (!ageGroupCode.equals(other.ageGroupCode)) {
			return false;
		}
		return true;
	}

}
