package com.soramame.web.model;

import java.io.Serializable;

/**
 * location_mst ÉÇÉfÉãÉNÉâÉX.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LocationMstModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** location_code. */
	private String locationCode;

	/** location_name. */
	private String locationName;

	/** sort_number. */
	private Integer sortNumber;
	
	/** select. */
	private String select;

	/**
	 * Constructor
	 * @param locationCode
	 * @param locationName
	 * @param select
	 */
	public LocationMstModel(String locationCode, String locationName, String select) {
		this.locationCode = locationCode;
		this.locationName = locationName;
		
		if (select.equals(locationCode)) {
			this.select = "selected";
			
		} else {
			this.select = "";
			
		}
	}

	/**
	 * location_code Çê›íËÇµÇ‹Ç∑.
	 * 
	 * @param locationCode
	 *            location_code
	 */
	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	/**
	 * location_code ÇéÊìæÇµÇ‹Ç∑.
	 * 
	 * @return location_code
	 */
	public String getLocationCode() {
		return this.locationCode;
	}

	/**
	 * location_name Çê›íËÇµÇ‹Ç∑.
	 * 
	 * @param locationName
	 *            location_name
	 */
	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	/**
	 * location_name ÇéÊìæÇµÇ‹Ç∑.
	 * 
	 * @return location_name
	 */
	public String getLocationName() {
		return this.locationName;
	}

	/**
	 * sort_number Çê›íËÇµÇ‹Ç∑.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number ÇéÊìæÇµÇ‹Ç∑.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * @return the select
	 */
	public String getSelect() {
		return select;
	}

	/**
	 * @param select the select to set
	 */
	public void setSelect(String select) {
		this.select = select;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((locationCode == null) ? 0 : locationCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		LocationMstModel other = (LocationMstModel) obj;
		if (locationCode == null) {
			if (other.locationCode != null) {
				return false;
			}
		} else if (!locationCode.equals(other.locationCode)) {
			return false;
		}
		return true;
	}

}
