package com.soramame.web.model;

import java.io.Serializable;

/**
 * recruitmentArea_mst ƒ‚ƒfƒ‹ƒNƒ‰ƒX.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RecruitmentAreaMstModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** recruitment_area_code. */
	private String recruitmentAreaCode;

	/** recruitment_area_name. */
	private String recruitmentAreaName;

	/** sort_number. */
	private Integer sortNumber;
	
	/** select. */
	private String select;

	/**
	 * Constructor
	 * @param recruitmentAreaCode
	 * @param recruitmentAreaName
	 * @param select
	 */
	public RecruitmentAreaMstModel(String recruitmentAreaCode, String recruitmentAreaName, String select) {
		this.recruitmentAreaCode = recruitmentAreaCode;
		this.recruitmentAreaName = recruitmentAreaName;
		
		if (select.equals(recruitmentAreaCode)) {
			this.select = "selected";
			
		} else {
			this.select = "";
			
		}
	}

	/**
	 * recruitment_area_code ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param recruitmentAreaCode
	 *            recruitmentArea_code
	 */
	public void setRecruitmentAreaCode(String recruitmentAreaCode) {
		this.recruitmentAreaCode = recruitmentAreaCode;
	}

	/**
	 * recruitment_area_code ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return recruitment_area_code
	 */
	public String getRecruitmentAreaCode() {
		return this.recruitmentAreaCode;
	}

	/**
	 * recruitment_area_name ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param recruitment_area_name
	 *            recruitment_area_name
	 */
	public void setRecruitmentAreaName(String recruitmentAreaName) {
		this.recruitmentAreaName = recruitmentAreaName;
	}

	/**
	 * recruitment_area_name ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return recruitment_area_name
	 */
	public String getRecruitmentAreaName() {
		return this.recruitmentAreaName;
	}

	/**
	 * sort_number ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * @return the select
	 */
	public String getSelect() {
		return select;
	}

	/**
	 * @param select the select to set
	 */
	public void setSelect(String select) {
		this.select = select;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((recruitmentAreaCode == null) ? 0 : recruitmentAreaCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RecruitmentAreaMstModel other = (RecruitmentAreaMstModel) obj;
		if (recruitmentAreaCode == null) {
			if (other.recruitmentAreaCode != null) {
				return false;
			}
		} else if (!recruitmentAreaCode.equals(other.recruitmentAreaCode)) {
			return false;
		}
		return true;
	}

}
