package com.soramame.web.model;

import java.io.Serializable;

/**
 * type_industry_mst ƒ‚ƒfƒ‹ƒNƒ‰ƒX.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TypeIndustryMstModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** type_industry_code. */
	private String typeIndustryCode;

	/** type_industry_name. */
	private String typeIndustryName;

	/** sort_number. */
	private Integer sortNumber;

	/** select. */
	private String select;
	
	/**
	 * Constructor
	 * @param typeIndustryCode
	 * @param typeIndustryName
	 * @param select
	 */
	public TypeIndustryMstModel(String typeIndustryCode, String typeIndustryName, String select) {
		this.typeIndustryCode = typeIndustryCode;
		this.typeIndustryName = typeIndustryName;
		
		if (select.equals(typeIndustryCode)) {
			this.select = "selected";
			
		} else {
			this.select = "";
			
		}
		
	}

	/**
	 * type_industry_code ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param typeIndustryCode
	 *            type_industry_code
	 */
	public void setTypeIndustryCode(String typeIndustryCode) {
		this.typeIndustryCode = typeIndustryCode;
	}

	/**
	 * type_industry_code ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return type_industry_code
	 */
	public String getTypeIndustryCode() {
		return this.typeIndustryCode;
	}

	/**
	 * type_industry_name ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param typeIndustryName
	 *            type_industry_name
	 */
	public void setTypeIndustryName(String typeIndustryName) {
		this.typeIndustryName = typeIndustryName;
	}

	/**
	 * type_industry_name ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return type_industry_name
	 */
	public String getTypeIndustryName() {
		return this.typeIndustryName;
	}

	/**
	 * sort_number ‚ğİ’è‚µ‚Ü‚·.
	 * 
	 * @param sortNumber
	 *            sort_number
	 */
	public void setSortNumber(Integer sortNumber) {
		this.sortNumber = sortNumber;
	}

	/**
	 * sort_number ‚ğæ“¾‚µ‚Ü‚·.
	 * 
	 * @return sort_number
	 */
	public Integer getSortNumber() {
		return this.sortNumber;
	}

	/**
	 * @return the select
	 */
	public String getSelect() {
		return select;
	}

	/**
	 * @param select the select to set
	 */
	public void setSelect(String select) {
		this.select = select;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((typeIndustryCode == null) ? 0 : typeIndustryCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TypeIndustryMstModel other = (TypeIndustryMstModel) obj;
		if (typeIndustryCode == null) {
			if (other.typeIndustryCode != null) {
				return false;
			}
		} else if (!typeIndustryCode.equals(other.typeIndustryCode)) {
			return false;
		}
		return true;
	}

}
