package com.soramame.web.model;

import java.io.Serializable;
import java.util.Date;

/**
 * player_access_counter モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserAccessCounterModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_name. */
	private String userName;

	/** player_access_count. */
	private Integer userAccessCount;

	/** access_date. */
	private Date accessDate;

	/**
	 * コンストラクタ.
	 */
	public UserAccessCounterModel() {
		userAccessCount = 0;
	}

	/**
	 * user_name を設定します.
	 * 
	 * @param userName
	 *            user_name
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * user_name を取得します.
	 * 
	 * @return user_name
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * player_access_count を設定します.
	 * 
	 * @param playerAccessCount
	 *            player_access_count
	 */
	public void setUserAccessCount(Integer playerAccessCount) {
		this.userAccessCount = playerAccessCount;
	}

	/**
	 * player_access_count を取得します.
	 * 
	 * @return player_access_count
	 */
	public Integer getUserAccessCount() {
		return this.userAccessCount;
	}

	/**
	 * access_date を設定します.
	 * 
	 * @param accessDate
	 *            access_date
	 */
	public void setAccessDate(Date accessDate) {
		this.accessDate = accessDate;
	}

	/**
	 * access_date を取得します.
	 * 
	 * @return access_date
	 */
	public Date getAccessDate() {
		return this.accessDate;
	}

}
